version: '3.7'

services:
      
  mycompanyname.abpzerotemplate.web.mvc:
    image: ${DOCKER_REGISTRY-}mycompanynameabpzerotemplatewebmvc
    container_name: mycompanynameabpzerotemplatewebmvc_container
    build:
      context: ../../
      dockerfile: src/CCPDemo.Web.Mvc/Dockerfile
    environment:
      - ConnectionStrings__Default=Server=mssqlDb;Database=CCPDemoDb;User=sa;Password=Super_Encrypted_Passw0rd!
      - Abp__RedisCache__ConnectionString=localhost:6379
    ports:
      - "44302:443"
    networks:
      - mycompanyname.abpzerotemplate

networks:
  mycompanyname.abpzerotemplate:
    external:
      name: mycompanyname.abpzerotemplate